version: 7
profiles: []
groups: []
configSync:
  parts: {}
hotkeys:
  toggle-window: []
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - ⌘-C
  paste:
    - ⌘-V
  clear:
    - ⌘-K
  select-all:
    - ⌘-A
  zoom-in:
    - ⌘-=
    - ⌘-Shift-=
  zoom-out:
    - ⌘--
    - ⌘-Shift--
  reset-zoom:
    - ⌘-0
  home:
    - ⌘-Left
    - Home
  end:
    - ⌘-Right
    - End
  previous-word:
    - ⌥-Left
  next-word:
    - ⌥-Right
  delete-previous-word:
    - ⌥-Backspace
  delete-line:
    - ⌘-Backspace
  delete-next-word:
    - ⌥-Delete
  search:
    - ⌘-F
  pane-focus-all:
    - ⌘-Shift-I
  focus-all-tabs:
    - ⌘-⌥-Shift-I
  scroll-to-top:
    - Shift-PageUp
  scroll-page-up:
    - ⌥-PageUp
  scroll-up:
    - Ctrl-Shift-Up
  scroll-down:
    - Ctrl-Shift-Down
  scroll-page-down:
    - ⌥-PageDown
  scroll-to-bottom:
    - Shift-PageDown
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab: {}
  settings:
    - ⌘-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-tab:
    - ⌘-T
  new-window:
    - ⌘-N
  profile: {}
  profile-selectors: {}
  group-selectors: {}
  toggle-fullscreen:
    - Ctrl+⌘+F
  close-tab:
    - ⌘-W
  reopen-tab:
    - ⌘-Shift-T
  toggle-last-tab: []
  rename-tab:
    - ⌘-R
  next-tab:
    - Ctrl-Tab
    - ⌘-Shift-]
  previous-tab:
    - Ctrl-Shift-Tab
    - ⌘-Shift-[
  move-tab-left:
    - ⌘-Shift-Left
  move-tab-right:
    - ⌘-Shift-Right
  rearrange-panes:
    - Ctrl-Shift
  tab-1:
    - ⌘-1
  tab-2:
    - ⌘-2
  tab-3:
    - ⌘-3
  tab-4:
    - ⌘-4
  tab-5:
    - ⌘-5
  tab-6:
    - ⌘-6
  tab-7:
    - ⌘-7
  tab-8:
    - ⌘-8
  tab-9:
    - ⌘-9
  tab-10: []
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab:
    - ⌘-Shift-.
  combine-tabs:
    - ⌘-Shift-,
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - ⌘-Shift-D
  split-bottom:
    - ⌘-D
  split-left: []
  split-top: []
  pane-nav-right:
    - ⌘-⌥-Right
  pane-nav-down:
    - ⌘-⌥-Down
  pane-nav-up:
    - ⌘-⌥-Up
  pane-nav-left:
    - ⌘-⌥-Left
  pane-nav-previous:
    - ⌘-⌥-[
  pane-nav-next:
    - ⌘-⌥-]
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - ⌘-⌥-Enter
  close-pane:
    - ⌘-Shift-W
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  profile-selector:
    - ⌘-E
  switch-profile:
    - ⌘-Shift-E
  command-selector:
    - ⌘-Shift-P
terminal:
  searchOptions: {}
  colorScheme:
    name: Tabby Default
    foreground: '#cacaca'
    background: '#171717'
    cursor: '#bbbbbb'
    colors:
      - '#000000'
      - '#ff615a'
      - '#b1e969'
      - '#ebd99c'
      - '#5da9f6'
      - '#e86aff'
      - '#82fff7'
      - '#dedacf'
      - '#313131'
      - '#f58c80'
      - '#ddf88f'
      - '#eee5b2'
      - '#a5c7ff'
      - '#ddaaff'
      - '#b7fff9'
      - '#ffffff'
  font: Hack Nerd Font
  fontSize: 13
  lightColorScheme:
    name: Tabby Default Light
    foreground: '#4d4d4c'
    background: '#ffffff'
    cursor: '#4d4d4c'
    colors:
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
  fallbackFont: Consolas
  warnOnMultilinePaste: false
  customColorSchemes:
    - name: custom
      foreground: '#d4d4d4'
      background: 1e1e1e
      cursor: '#bbbbbb'
      colors:
        - '#000000'
        - '#ff615a'
        - '#b1e969'
        - '#ebd99c'
        - '#5da9f6'
        - '#e86aff'
        - '#82fff7'
        - '#dedacf'
        - '#313131'
        - '#f58c80'
        - '#ddf88f'
        - '#eee5b2'
        - '#a5c7ff'
        - '#ddaaff'
        - '#b7fff9'
        - '#ffffff'
ssh: {}
clickableLinks: {}
accessibility:
  animations: false
appearance: {}
hacks: {}
providerBlacklist: []
commandBlacklist: []
language: en-US
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist: []
profileDefaults:
  ssh:
    disableDynamicTitle: true
profileBlacklist: []
