apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb
resources:
  - github.com/metallb/metallb//manifests?ref=v0.9.6
  - ../configmap.yaml
  # - ../configmap-kind.yaml
  # - ../configmap-minikube.yaml
  - memberlist-secret-temp.yaml
