# https://github.com/helm/charts/tree/master/stable/chartmuseum
---
env:
  open:
    STORAGE: "amazon"
    STORAGE_AMAZON_BUCKET: "mychart"
    # STORAGE_AMAZON_PREFIX:
    # STORAGE_AMAZON_REGION:
    STORAGE_AMAZON_ENDPOINT: "http://my-minio.minio-system:9000"
  secret:
    AWS_ACCESS_KEY_ID: "admin"
    AWS_SECRET_ACCESS_KEY: "changeit"
